export const configureSagaActions = {
  GET_USER_DATA_YOUTUBE: "GET_USER_DATA_YOUTUBE",
  GET_YOUTUBE_MEDIA: "GET_YOUTUBE_MEDIA",
  GET_USER_DATA_FACEBOOK: "GET_USER_DATA_FACEBOOK",
  GET_FACEBOOK_MEDIA: "GET_FACEBOOK_MEDIA",
  GET_USER_DATA_IG: "GET_USER_DATA_IG",
  GET_IG_MEDIA: "GET_IG_MEDIA",
  GET_IMPORTED_MEDIA: "GET_IMPORTED_MEDIA",
  SET_SECTIONS: "SET_SECTIONS",
  SET_IMPORTED_YT_MEDIA: "SET_IMPORTED_YT_MEDIA",
  SET_IMPORTED_FB_MEDIA: "SET_IMPORTED_FB_MEDIA",
  SET_IMPORTED_IG_MEDIA: "SET_IMPORTED_IG_MEDIA",
  RESET_YT_DATA: "RESET_YT_DATA",
  RESET_FB_DATA: "RESET_FB_DATA",
  RESET_IG_DATA: "RESET_IG_DATA"
};
