export const onboardingSagaActions = {
  CREATE_AWS_ACCOUNT: "CREATE_AWS_ACCOUNT",
  VALIDATE_USERNAME: "VALIDATE_USERNAME",
  EDIT_USER: "EDIT_USER",
  SET_ID: "SET_ID",
  TOGGLE_THEME: "TOGGLE_THEME",
  SET_ACTIVE_SECTION: "SET_ACTIVE_SECTION",
};
