export const MEDIA_URL = process.env.NEXT_PUBLIC_MEDIA_PROD_URL;
export const YOUTUBE_APIKEY = process.env.NEXT_PUBLIC_YOUTUBE_APIKEY;
export const YOUTUBE_CLIENT_ID = process.env.NEXT_PUBLIC_YOUTUBE_CLIENT_ID;
export const YOUTUBE_VIDEO_SCOPES =
  process.env.NEXT_PUBLIC_YOUTUBE_VIDEO_SCOPES;
export const YOUTUBE_ANALYTICS_SCOPES =
  process.env.NEXT_PUBLIC_YOUTUBE_ANALYTICS_SCOPES;
export const FACEBOOK_CLIENT_ID = process.env.NEXT_PUBLIC_FACEBOOK_CLIENT_ID;
export const FACEBOOK_SCOPES = process.env.NEXT_PUBLIC_FACEBOOK_SCOPES;
export const INSTAGRAM_SCOPES = process.env.NEXT_PUBLIC_INSTAGRAM_SCOPES;
export const INSTAGRAM_ANALYTICS_SCOPES =
  process.env.NEXT_PUBLIC_INSTAGRAM_ANALYTICS_SCOPES;
export const REDIRECT_SIGN_IN_URI =
  process.env.NEXT_PUBLIC_REDIRECT_SIGN_IN_URI;
export const REDIRECT_SIGN_OUT_URI =
  process.env.NEXT_PUBLIC_REDIRECT_SIGN_OUT_URI;
export const YOUTUBE_SHORT_REDIRECT_URI =
  process.env.NEXT_PUBLIC_YOUTUBE_SHORT_REDIRECT_URI;
export const GOOGLE_ANALYTICS_ID = process.env.NEXT_PUBLIC_GOOGLE_ANALYTICS_ID;
